services:

  ${projectName}:
    container_name: ${projectName}
    image: ${containerImageRegistry}/${containerImageGroup}/${projectName}:${version}
    ports:
      - "${hostPort}:${containerPort}"
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      QUARKUS_DATASOURCE_JDBC_URL: "${jdbcURL}"
      QUARKUS_DATASOURCE_REACTIVE_URL: "${reactiveURL}"
      QUARKUS_DATASOURCE_USERNAME: ${dbUser}
      QUARKUS_DATASOURCE_PASSWORD: ${dbPassword}
      QUARKUS_DATASOURCE_DB_KIND: ${dbKind}
      KOGITO_JOBS_SERVICE_URL: ${kogitoJobsServiceURL}
      KOGITO_SERVICE_URL: ${kogitoServiceURL}
      KOGITO_DATAINDEX_HTTP_URL: ${kogitoDataIndexURL}
    extra_hosts:
      - "127.0.0.1:host-gateway"